version: "3.3"

services:

  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
       - ./pgdata:/var/lib/postgresql/data
       - ./001.sql:/docker-entrypoint-initdb.d/001.sql
       - ./002.sql:/docker-entrypoint-initdb.d/002.sql
    # network_mode: 'host'
    ports:
      - 5433:5432